name: build

on:
  #push:
  #  branches-ignore: ["main"]
  pull_request:
    branches: ["main"]
    # ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
    paths-ignore:
    - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          # depth=0 is needed by build_then_push.sh
          fetch-depth: 0
          persist-credentials: false
      - name: Docker toolchains
        run: docker version
      #      - name: Login to GitHub Container Registry
      #        uses: docker/login-action@v1
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.repository_owner }}
      #          password: ${{ secrets.GHCR_TOKEN }}
      #      - name: Build and push the docker images
      #        run: bash build_then_push.sh ghcr.io/sammyne
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the docker images
        run: bash build_then_push.sh ${{ github.repository_owner }}
